[sysmon_event1_ntds_exfil]
sampletype = raw
backfill = -15m
interval = 10
count = 2
breaker = \n
earliest = -1h
latest = now
generator = replay

token.0.token = \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}
token.0.replacementType = timestamp
token.0.replacement = %Y-%m-%d %H:%M:%S.%f

token.1.token = (?<=CommandLine: ).+
token.1.replacementType = random
token.1.replacement = choice[
    "ntds.dit -d ntds.dit -o hash.txt -s system.hiv",
    "powershell 'ntdsutil.exe \"ac i ntds\" \"ifm\" \"create full c:\\temp\" q q'",
    "cmd.exe /c copy z:\\windows\\ntds\\ntds.dit c:\\exfil\\ntds.dit",
    "ntdsutil \"activate instance ntds\" \"ifm\" \"create full c:\\windows\\temp\\data\\\" \"quit\" \"quit\""
]

token.2.token = (?<=Image: ).+
token.2.replacementType = random
token.2.replacement = choice["C:\\Windows\\System32\\ntdsutil.exe", "C:\\Windows\\System32\\cmd.exe"]

token.3.token = (?<=ParentImage: ).+
token.3.replacementType = random
token.3.replacement = choice["C:\\Windows\\System32\\services.exe", "C:\\Windows\\System32\\lsass.exe"]
