[ProcessRollup2.log]
mode = replay
sampletype = json
token.0.token = "ImageFileName": ".*?"
token.0.replacementType = replay
token.0.replacement = "ImageFileName": "{atomic_red_team_imagefilename}"
token.1.token = "CommandLine": ".*?"
token.1.replacementType = replay
token.1.replacement = "CommandLine": "{atomic_red_team_commandline}"
backfill = -15m
interval = 5
outputMode = splunkstream
breaker = ^\{